services:
  postgres:
    image: postgres:15
    container_name: postgres_academico
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2U5iFr654osI
      POSTGRES_DB: academico
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  academico-back:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
